import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-retail-returns-liquidation-recovery",
  "engine": "recovery",
  "title": "Retail Returns & Liquidation Recovery",
  "shortTitle": "Retail Returns and Liquidation Recovery",
  "tagline": "Maximize recovery from returned inventory through condition validation, routing, refurbishment, liquidation, and settlement controls.",
  "industry": "Retail Reverse Logistics",
  "buyer": "Retailers and consumer brands",
  "uiPort": 4733,
  "apiPort": 5733,
  "accent": "#0369a1",
  "currency": "USD",
  "primaryOutcome": "Retail Returns & Liquidation Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect return policies, RMAs, products, condition grades, carrier events, warehouse receipts, refurbishment, liquidation lots, fees, settlements, and cash in one accountable workflow. Maximize recovery from returned inventory through condition validation, routing, refurbishment, liquidation, and settlement controls.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Retail Returns & Liquidation Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("return-policy-library","RRL01","Return policy library","Execute return policy library using return policies, RMAs, products, condition grades, carrier events, warehouse receipts, refurbishment, liquidation lots, fees, settlements, and cash.","Produce a governed return policy library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Channel / Returned Inventory","text","Channel / Returned Inventory · Standard Case"],["caseReference","Return policy library Reference","text","RRL01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1745000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2111450],["domainDriver","Disposition","select","Restock",["Restock","Refurbish","Liquidate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Return policy library case","RMA ingestion case","Carrier event tracking case","Warehouse receipt matching case","Condition grade validation case"]}),
feature("rma-ingestion","RRL02","RMA ingestion","Execute rma ingestion using return policies, RMAs, products, condition grades, carrier events, warehouse receipts, refurbishment, liquidation lots, fees, settlements, and cash.","Produce a governed rma ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Channel / Returned Inventory","text","Channel / Returned Inventory · Standard Case"],["caseReference","RMA ingestion Reference","text","RRL02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1745000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2111450],["domainDriver","Disposition","select","Restock",["Restock","Refurbish","Liquidate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Return policy library case","RMA ingestion case","Carrier event tracking case","Warehouse receipt matching case","Condition grade validation case"]}),
feature("carrier-event-tracking","RRL03","Carrier event tracking","Execute carrier event tracking using return policies, RMAs, products, condition grades, carrier events, warehouse receipts, refurbishment, liquidation lots, fees, settlements, and cash.","Produce a governed carrier event tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Channel / Returned Inventory","text","Channel / Returned Inventory · Standard Case"],["caseReference","Carrier event tracking Reference","text","RRL03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1745000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2111450],["domainDriver","Disposition","select","Restock",["Restock","Refurbish","Liquidate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Return policy library case","RMA ingestion case","Carrier event tracking case","Warehouse receipt matching case","Condition grade validation case"]}),
feature("warehouse-receipt-matching","RRL04","Warehouse receipt matching","Execute warehouse receipt matching using return policies, RMAs, products, condition grades, carrier events, warehouse receipts, refurbishment, liquidation lots, fees, settlements, and cash.","Produce a governed warehouse receipt matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Channel / Returned Inventory","text","Channel / Returned Inventory · Standard Case"],["caseReference","Warehouse receipt matching Reference","text","RRL04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1745000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2111450],["domainDriver","Disposition","select","Restock",["Restock","Refurbish","Liquidate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Return policy library case","RMA ingestion case","Carrier event tracking case","Warehouse receipt matching case","Condition grade validation case"]}),
feature("condition-grade-validation","RRL05","Condition grade validation","Execute condition grade validation using return policies, RMAs, products, condition grades, carrier events, warehouse receipts, refurbishment, liquidation lots, fees, settlements, and cash.","Produce a governed condition grade validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Channel / Returned Inventory","text","Channel / Returned Inventory · Standard Case"],["caseReference","Condition grade validation Reference","text","RRL05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1745000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2111450],["domainDriver","Disposition","select","Restock",["Restock","Refurbish","Liquidate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Return policy library case","RMA ingestion case","Carrier event tracking case","Warehouse receipt matching case","Condition grade validation case"]}),
feature("restock-eligibility","RRL06","Restock eligibility","Execute restock eligibility using return policies, RMAs, products, condition grades, carrier events, warehouse receipts, refurbishment, liquidation lots, fees, settlements, and cash.","Produce a governed restock eligibility decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Channel / Returned Inventory","text","Channel / Returned Inventory · Standard Case"],["caseReference","Restock eligibility Reference","text","RRL06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1745000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2111450],["domainDriver","Disposition","select","Restock",["Restock","Refurbish","Liquidate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Return policy library case","RMA ingestion case","Carrier event tracking case","Warehouse receipt matching case","Condition grade validation case"]}),
feature("refurbishment-economics","RRL07","Refurbishment economics","Execute refurbishment economics using return policies, RMAs, products, condition grades, carrier events, warehouse receipts, refurbishment, liquidation lots, fees, settlements, and cash.","Produce a governed refurbishment economics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Channel / Returned Inventory","text","Channel / Returned Inventory · Standard Case"],["caseReference","Refurbishment economics Reference","text","RRL07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1745000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2111450],["domainDriver","Disposition","select","Restock",["Restock","Refurbish","Liquidate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Return policy library case","RMA ingestion case","Carrier event tracking case","Warehouse receipt matching case","Condition grade validation case"]}),
feature("liquidation-lot-creation","RRL08","Liquidation lot creation","Execute liquidation lot creation using return policies, RMAs, products, condition grades, carrier events, warehouse receipts, refurbishment, liquidation lots, fees, settlements, and cash.","Produce a governed liquidation lot creation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Channel / Returned Inventory","text","Channel / Returned Inventory · Standard Case"],["caseReference","Liquidation lot creation Reference","text","RRL08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1745000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2111450],["domainDriver","Disposition","select","Restock",["Restock","Refurbish","Liquidate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Return policy library case","RMA ingestion case","Carrier event tracking case","Warehouse receipt matching case","Condition grade validation case"]}),
feature("expected-resale-value","RRL09","Expected resale value","Execute expected resale value using return policies, RMAs, products, condition grades, carrier events, warehouse receipts, refurbishment, liquidation lots, fees, settlements, and cash.","Produce a governed expected resale value decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Channel / Returned Inventory","text","Channel / Returned Inventory · Standard Case"],["caseReference","Expected resale value Reference","text","RRL09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1745000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2111450],["domainDriver","Disposition","select","Restock",["Restock","Refurbish","Liquidate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Return policy library case","RMA ingestion case","Carrier event tracking case","Warehouse receipt matching case","Condition grade validation case"]}),
feature("channel-fee-audit","RRL10","Channel fee audit","Execute channel fee audit using return policies, RMAs, products, condition grades, carrier events, warehouse receipts, refurbishment, liquidation lots, fees, settlements, and cash.","Produce a governed channel fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Channel / Returned Inventory","text","Channel / Returned Inventory · Standard Case"],["caseReference","Channel fee audit Reference","text","RRL10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1745000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2111450],["domainDriver","Disposition","select","Restock",["Restock","Refurbish","Liquidate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Return policy library case","RMA ingestion case","Carrier event tracking case","Warehouse receipt matching case","Condition grade validation case"]}),
feature("missing-unit-detection","RRL11","Missing unit detection","Execute missing unit detection using return policies, RMAs, products, condition grades, carrier events, warehouse receipts, refurbishment, liquidation lots, fees, settlements, and cash.","Produce a governed missing unit detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Channel / Returned Inventory","text","Channel / Returned Inventory · Standard Case"],["caseReference","Missing unit detection Reference","text","RRL11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1745000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2111450],["domainDriver","Disposition","select","Restock",["Restock","Refurbish","Liquidate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Return policy library case","RMA ingestion case","Carrier event tracking case","Warehouse receipt matching case","Condition grade validation case"]}),
feature("liquidator-statement-reconciliation","RRL12","Liquidator statement reconciliation","Execute liquidator statement reconciliation using return policies, RMAs, products, condition grades, carrier events, warehouse receipts, refurbishment, liquidation lots, fees, settlements, and cash.","Produce a governed liquidator statement reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Channel / Returned Inventory","text","Channel / Returned Inventory · Standard Case"],["caseReference","Liquidator statement reconciliation Reference","text","RRL12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1745000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2111450],["domainDriver","Disposition","select","Restock",["Restock","Refurbish","Liquidate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Return policy library case","RMA ingestion case","Carrier event tracking case","Warehouse receipt matching case","Condition grade validation case"]}),
feature("dispute-workflow","RRL13","Dispute workflow","Execute dispute workflow using return policies, RMAs, products, condition grades, carrier events, warehouse receipts, refurbishment, liquidation lots, fees, settlements, and cash.","Produce a governed dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Channel / Returned Inventory","text","Channel / Returned Inventory · Standard Case"],["caseReference","Dispute workflow Reference","text","RRL13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1745000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2111450],["domainDriver","Disposition","select","Restock",["Restock","Refurbish","Liquidate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Return policy library case","RMA ingestion case","Carrier event tracking case","Warehouse receipt matching case","Condition grade validation case"]}),
feature("cash-recovery-tracking","RRL14","Cash recovery tracking","Execute cash recovery tracking using return policies, RMAs, products, condition grades, carrier events, warehouse receipts, refurbishment, liquidation lots, fees, settlements, and cash.","Produce a governed cash recovery tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Channel / Returned Inventory","text","Channel / Returned Inventory · Standard Case"],["caseReference","Cash recovery tracking Reference","text","RRL14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1745000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2111450],["domainDriver","Disposition","select","Restock",["Restock","Refurbish","Liquidate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Return policy library case","RMA ingestion case","Carrier event tracking case","Warehouse receipt matching case","Condition grade validation case"]}),
feature("product-disposition-analytics","RRL15","Product disposition analytics","Execute product disposition analytics using return policies, RMAs, products, condition grades, carrier events, warehouse receipts, refurbishment, liquidation lots, fees, settlements, and cash.","Produce a governed product disposition analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Channel / Returned Inventory","text","Channel / Returned Inventory · Standard Case"],["caseReference","Product disposition analytics Reference","text","RRL15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1745000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2111450],["domainDriver","Disposition","select","Restock",["Restock","Refurbish","Liquidate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Return policy library case","RMA ingestion case","Carrier event tracking case","Warehouse receipt matching case","Condition grade validation case"]})
]);
